package com.entrada.cheekyMonkey.db;

public class DBStatements implements DBConstants {

    /**
     * Create Statement for USR_Table ******************
     */
    public static final String CREATE_USR_TABLE = CREATE_TABLE_BASE
            + KEY_USR_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_USR_USERNAME + TEXT + COMMA
            + KEY_USR_PASSWORD + TEXT + COMMA + KEY_USR_POS_CODE + TEXT + COMMA
            + KEY_USR_TOKEN + TEXT + COMMA + KEY_USR_SERVER_ID + TEXT + COMMA
            + KEY_USR_LANGUAGE + TEXT + COMMA + KEY_USR_THEME_BCKGRND_COLOR
            + TEXT + COMMA + KEY_USR_THEME_FONT_COLOR + TEXT + COMMA
            + KEY_COMP_CODE + TEXT + COMMA + KEY_RUNNING_DATE + TEXT + FINISH_COLUMN;


    /**
     * Create Statement for RMS_Outlet_Table ******************
     */

    public static final String CREATE_RMS_OUTLET_TABLE = CREATE_TABLE_BASE
            + KEY_OUTLET_TABLE_NAME + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_OUTLET_TABLE_OUTLET_NAME + TEXT + COMMA
            + KEY_OUTLET_TABLE_LOCATION + TEXT + COMMA
            + KEY_OUTLET_TABLE_CITY + TEXT + COMMA + KEY_OUTLET_TABLE_OUTLET_CODE
            + TEXT + FINISH_COLUMN;



    /**
     * Create Statement for Outlet_Pos Table ******************
     */
    public static final String CREATE_OUTLET_POS_TABLE = CREATE_TABLE_BASE
            + KEY_OUTLET_POS_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_OUTLET_POS_CODE + TEXT + COMMA
            + KEY_OUTLET_POS_NAME + TEXT + COMMA + KEY_OUTLET_POS_TYPE + TEXT
            + COMMA + KEY_OUTLET_POS_HEADER + TEXT + COMMA
            + KEY_OUTLET_POS_FOOTER + TEXT + FINISH_COLUMN;

    /**
     * Create Statement for Outlet_table ***********************
     */
    public static final String CREATE_OUTLET_TABLE = CREATE_TABLE_BASE
            + KEY_OUTLET_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_OUTLET_TABLE_POS_CODE + TEXT + COMMA
            + KEY_OUTLET_TABLE_CODE + TEXT + COMMA + KEY_OUTLET_TABLE_NUM
            + TEXT + FINISH_COLUMN;

    /**
     * Create Statement for GROUP_table ***********************
     */
    public static final String CREATE_GROUP_TABLE = CREATE_TABLE_BASE
            + KEY_GROUP_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_GROUP_CODE + TEXT + COMMA
            + KEY_GROUP_COLOR + TEXT + COMMA + KEY_GROUP_Name + TEXT
            + FINISH_COLUMN;

    public static final String CREATE_CATEGORY_TABLE = CREATE_TABLE_BASE
            + KEY_CATEGORY_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_CATEGORY_POS_CODE + TEXT + COMMA
            + KEY_CAT_CODE + TEXT + COMMA + KEY_CAT_COLOR + TEXT + COMMA
            + KEY_CAT_NAME + TEXT + COMMA + KEY_CAT_GRP_CODE + TEXT
            + FINISH_COLUMN;

    public static final String CREATE_MENU_ITEM_TABLE = CREATE_TABLE_BASE
            + KEY_MENU_ITEM_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_MENU_POS_CODE + TEXT + COMMA
            + KEY_MENU_CODE + TEXT + COMMA + KEY_MENU_NAME + TEXT + COMMA
            + KEY_MENU_CAT_CODE + TEXT + COMMA + KEY_MENU_COLOR + TEXT + COMMA
            + KEY_MENU_GRP_CODE + TEXT + COMMA + KEY_MENU_PRICE + TEXT + COMMA
            + KEY_MENU_VAT + TEXT + COMMA + KEY_MENU_SUB_UNIT + TEXT + COMMA
            + KEY_MENU_COMBO_FLAG + TEXT + COMMA + KEY_MENU_ADDON_FLAG + TEXT
            + COMMA + KEY_MENU_MODIFIER + TEXT + COMMA + KEY_MENU_OPEN_ITEM
            + TEXT + COMMA + KEY_MENU_SUB_ITEM + TEXT + COMMA
            + KEY_MENU_VEG_NON + TEXT + COMMA + KEY_MENU_CALORIES + TEXT
            + COMMA + KEY_MENU_ITEM_DYNAMIC + TEXT + FINISH_COLUMN;

    public static final String CREATE_ADDON_ITEM_TABLE = CREATE_TABLE_BASE
            + KEY_ADDONS_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_ADDON_POS_CODE + TEXT + COMMA
            + KEY_ADDONS_ITEM_CODE + TEXT + COMMA + KEY_ADDONS_CODE + TEXT
            + COMMA + KEY_ADDONS_NAME + TEXT + COMMA + KEY_ADDONS_COLOR + TEXT
            + COMMA + KEY_ADDONS_PRICE + TEXT + FINISH_COLUMN;

    public static final String CREATE_MODIFIER_TABLE = CREATE_TABLE_BASE
            + KEY_MODIFIER_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_MODIFIER_POS_CODE + TEXT + COMMA
            + KEY_MODIFIER_ITEM_CODE + TEXT + COMMA + KEY_MODIFIER_CODE + TEXT
            + COMMA + KEY_MODIFIER_NAME + TEXT + COMMA + KEY_MODIFIER_COLOR
            + TEXT + FINISH_COLUMN;

    public static final String CREATE_COMBO_TABLE = CREATE_TABLE_BASE
            + KEY_COMBO_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_COMBO_POS_CODE + TEXT + COMMA
            + KEY_COMBO_CODE + TEXT + COMMA + KEY_COMBO_ITEM_CODE + TEXT
            + COMMA + KEY_COMBO_NAME + TEXT + COMMA + KEY_COMBO_QTY + TEXT
            + COMMA + KEY_COMBO_MAX_QTY + TEXT + COMMA + KEY_COMBO_FLAG + TEXT
            + COMMA + KEY_COMBO_CAT_CODE + TEXT + COMMA + KEY_COMBO_CAT_NAME
            + TEXT + FINISH_COLUMN;

    public static final String CREATE_ITEM_REMARK_TABLE = CREATE_TABLE_BASE
            + KEY_ITEM_REMARK_TABLE + START_COLUMN + _ID + INTEGER
            + PRIMARY_KEY + AUTO_ICNREMENT + COMMA + KEY_ITEM_REMARK_CODE
            + TEXT + COMMA + KEY_ITEM_REMARK_DESC + TEXT + FINISH_COLUMN;

    public static final String CREATE_ORDER_REMARK_TABLE = CREATE_TABLE_BASE
            + KEY_ORDER_REMARK_TABLE + START_COLUMN + _ID + INTEGER
            + PRIMARY_KEY + AUTO_ICNREMENT + COMMA + KEY_ORDER_REMARK_CODE
            + TEXT + COMMA + KEY_ORDER_REMARK_DESC + TEXT + FINISH_COLUMN;

    public static final String CREATE_KITCHEN_MASTER_TABLE = CREATE_TABLE_BASE
            + KEY_KITCHEN_MASTER_TABLE + START_COLUMN + _ID + INTEGER
            + PRIMARY_KEY + AUTO_ICNREMENT + COMMA + KEY_KITCHEN_MASTER_CODE
            + TEXT + COMMA + KEY_KITCHEN_MASTER_NAME + TEXT + FINISH_COLUMN;

    public static final String CREATE_KITCHEN_REMARK_TABLE = CREATE_TABLE_BASE
            + KEY_KITCHEN_REMARK_TABLE + START_COLUMN + _ID + INTEGER
            + PRIMARY_KEY + AUTO_ICNREMENT + COMMA + KEY_KITCHEN_REMARK_CODE
            + TEXT + COMMA + KEY_KITCHEN_REMARK_NAME + TEXT + FINISH_COLUMN;

    public static final String CREATE_GUEST_TYPE_TABLE = CREATE_TABLE_BASE
            + KEY_GUEST_TYPE_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_GUEST_TYPE_CODE + TEXT + COMMA
            + KEY_GUEST_TYPE_NAME + TEXT + FINISH_COLUMN;

    public static final String CREATE_COMPLIMENTARY_TABLE = CREATE_TABLE_BASE
            + KEY_COMPLIMENTARY_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_COMPLIMENTARY_CODE + TEXT + COMMA
            + KEY_COMPLIMENTARY_NAME + TEXT + FINISH_COLUMN;

    public static final String CREATE_STEWARD_TYPE_TABLE = CREATE_TABLE_BASE
            + KEY_STEWARD_TYPE_TABLE + START_COLUMN + _ID + INTEGER
            + PRIMARY_KEY + AUTO_ICNREMENT + COMMA + KEY_STEWARD_TYPE_CODE
            + TEXT + COMMA + KEY_STEWARD_TYPE_NAME + TEXT + COMMA
            + KEY_STEWARD_TYPE_USER_ID + TEXT + FINISH_COLUMN;

    public static final String CREATE_DISC_MST_TABLE = CREATE_TABLE_BASE
            + KEY_DISC_MST_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_DISC_MST_POS_CODE + TEXT + COMMA
            + KEY_DISC_MST_DISC_CODE + TEXT + COMMA + KEY_DISC_MST_FROM_DATE
            + TEXT + COMMA + KEY_DISC_MST_TO_DATE + TEXT + COMMA
            + KEY_DISC_MST_FROM_TIME + TEXT + COMMA + KEY_DISC_MST_TO_TIME
            + TEXT + COMMA + KEY_DISC_MST_DISC_ACTIVE + TEXT + COMMA
            + KEY_DISC_MST_DISC_FLAG + TEXT + COMMA + KEY_DISC_MST_DISC_DESC + TEXT + COMMA + KEY_DISC_MST_DISC_FL + TEXT + COMMA
            + KEY_DISC_MST_DISC_TL + TEXT + COMMA + KEY_DISC_MST_DISC_OPN
            + TEXT + COMMA + KEY_DISC_MST_DISC_FLAT_FLAG + TEXT
            + COMMA + KEY_DISC_MST_DISC_OGI + TEXT + FINISH_COLUMN;


    public static final String CREATE_DISC_DOW_TABLE = CREATE_TABLE_BASE
            + KEY_DISC_DOW_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_DISC_DOW_POS_CODE + TEXT + COMMA
            + KEY_DISC_DOW_DISC_CODE + TEXT + COMMA + KEY_DISC_DOW_DAY + TEXT
            + FINISH_COLUMN;

    public static final String CREATE_DISC_ITEM_TABLE = CREATE_TABLE_BASE
            + KEY_DISC_ITEM_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_DISC_ITEM_POS_CODE + TEXT + COMMA
            + KEY_DISC_ITEM_DISC_CODE + TEXT + COMMA + KEY_DISC_ITEM_ITEM_CODE
            + TEXT + COMMA + KEY_DISC_ITEM_DISC_PER + TEXT + COMMA
            + KEY_DISC_ITEM_BILLED_QTY + TEXT + COMMA
            + KEY_DISC_ITEM_FREE_QTY + TEXT + COMMA
            + KEY_DISC_FREE_ITEM_CODE + TEXT + COMMA
            + KEY_DISC_HAPPY_RATE + TEXT + FINISH_COLUMN;

    public static final String CREATE_DISC_SUB_ITEM_TABLE = CREATE_TABLE_BASE
            + KEY_SUB_ITEM_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_SUB_ITEM_MENU_CODE + TEXT + COMMA
            + KEY_SUB_ITEM_SUB_CODE + TEXT + COMMA + KEY_SUB_ITEM_SUB_NAME
            + TEXT + COMMA + KEY_SUB_ITEM_POS + TEXT + COMMA
            + KEY_SUB_ITEM_SUB_RATE + TEXT + FINISH_COLUMN;

    public static final String CREATE_MEAL_TABLE = CREATE_TABLE_BASE
            + KEY_MEAL_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_MEAL_CODE + TEXT + COMMA
            + KEY_MEAL_DESC + TEXT + COMMA + KEY_MEAL_PRN_ODR + TEXT
            + FINISH_COLUMN;

    public static final String CREATE_ORDER_TYPE_TABLE = CREATE_TABLE_BASE
            + KEY_ORDER_TYPE_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_ORDER_TYPE_DESC + TEXT
            + FINISH_COLUMN;

    public static final String CREATE_GUEST_DISCOUNT_TABLE = CREATE_TABLE_BASE
            + KEY_GUEST_DISCOUNT_TABLE + START_COLUMN + _ID + INTEGER
            + PRIMARY_KEY + AUTO_ICNREMENT + COMMA + KEY_GUEST_DIS_GUEST_CODE
            + TEXT + COMMA + KEY_GUEST_DIS_GUEST_DISCOUNT + TEXT + COMMA
            + KEY_GUEST_DIS_GUEST_GRP_CODE + TEXT + FINISH_COLUMN;

    public static final String CREATE_KEY_HSSURCHR_DOW = CREATE_TABLE_BASE
            + KEY_HSSURCHR_DOW + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_SURCHARGE_POS_CODE + TEXT + COMMA
            + KEY_SURCHARGE_DISC_CODE + TEXT + COMMA + KEY_SURCHARGE + TEXT
            + FINISH_COLUMN;

    public static final String CREATE_KEY_HSSURCHR_MST = CREATE_TABLE_BASE
            + KEY_HSSURCHR_MST + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_SURCHARGE_MST_POS_CODE + TEXT
            + COMMA + KEY_SURCHARGE_MST_DISC_CODE + TEXT + COMMA
            + KEY_SURCHARGE_MST_FROM_DATE + TEXT + COMMA
            + KEY_SURCHARGE_MST_TO_DATE + TEXT + COMMA
            + KEY_SURCHARGE_MST_FROM_TIME + TEXT + COMMA
            + KEY_SURCHARGE_MST_TO_TIME + TEXT + COMMA
            + KEY_SURCHARGE_MST_DISC_ACT + TEXT + COMMA
            + KEY_SURCHARGE_MST_DISC_OG1 + TEXT + COMMA
            + KEY_SURCHARGE_MST_DISC_FL + TEXT + COMMA
            + KEY_SURCHARGE_MST_DISC_TL + TEXT + COMMA
            + KEY_SURCHARGE_MST_DISC_PER + TEXT + FINISH_COLUMN;

    public static final String CREATE_KEY_HSSURCHG_ITEM = CREATE_TABLE_BASE
            + KEY_HSSURCHG_ITEM + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_HSSURCHG_ITM_POS_CODE + TEXT + COMMA
            + KEY_HSSURCHG_ITM_DISC_CODE + TEXT + COMMA
            + KEY_HSSURCHG_ITM_ITEM_CODE + TEXT + COMMA
            + KEY_HSSURCHG_ITM_DISC_PER + TEXT + FINISH_COLUMN;

    public static final String CREATE_KEY_GUEST_TITLE = CREATE_TABLE_BASE
            + KEY_GUEST_TITLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_GUEST_TITL_CODE + TEXT + COMMA
            + KEY_GUEST_TITL_ABOUT + TEXT + COMMA + KEY_GUEST_TITL_DESC + TEXT
            + FINISH_COLUMN;

    public static final String CREATE_KEY_STEWARD_DETAIL = CREATE_TABLE_BASE
            + KEY_EMP_DETAIL + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_EMP_CODE + TEXT + COMMA
            + KEY_EMP_NAME + TEXT + COMMA + KEY_EMP_USER_ID + TEXT
            + COMMA + KEY_EMP_TYPE + TEXT + FINISH_COLUMN;

    public static final String CREATE_KEY_ABT_ITEM_IMAGE = CREATE_TABLE_BASE
            + KEY_ABT_ITEM_IMAGE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_ABT_CODE + TEXT + COMMA
            + KEY_ABT_ABOUT + TEXT + FINISH_COLUMN;
    public static final String CREATE_KEY_GUEST_PERMISION = CREATE_TABLE_BASE
            + KEY_GUEST_PERMISION + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_GUEST_GUEST_MAC + TEXT + COMMA
            + KEY_GUEST_GUEST_PERMISISON_CODE + TEXT + FINISH_COLUMN;

    public static final String CREATE_KEY_MANDATORY = CREATE_TABLE_BASE
            + KEY_MANDATORY_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_MD_COVER_ACTIVE + TEXT + COMMA
            + KEY_MD_COVER_MANDATORY + TEXT + COMMA + KEY_MD_STEWARD_ACTIVE
            + TEXT + COMMA + KEY_MD_STEWARD_MANDATORY + TEXT + COMMA
            + KEY_MD_MENU_CODE + TEXT + COMMA + KEY_MD_COVER_NO + TEXT + COMMA
            + KEY_MD_MEAL_COURSE + TEXT + COMMA + KEY_MD_MEAL_SURCHARGE_ACT
            + TEXT + FINISH_COLUMN;

    public static final String CREATE_KEY_PERMISSION = CREATE_TABLE_BASE
            + KEY_PERMISSION + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_PRM_USER_ID + TEXT + COMMA
            + KEY_PRM_MENU_VALUE + TEXT + COMMA + KEY_PRM_menu_id + TEXT
            + FINISH_COLUMN;

    public static final String CREATE_KEY_COMMENT_CARD = CREATE_TABLE_BASE
            + KEY_COMMENT_CARD + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + TEXT + COMMA + KEY_COMMENT_CARD + TEXT
            + COMMA + KEY_CC_PAR + TEXT + COMMA + KEY_CC_RATING + TEXT + COMMA
            + KEY_CC_FLAG + TEXT + FINISH_COLUMN;


    public static final String CREATE_GUEST_SEARCH_TABLE = CREATE_TABLE_BASE
            + KEY_GUEST_SEARCH_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_GUEST_NAME + TEXT + COMMA
            + KEY_GUEST_PHONE + TEXT + COMMA + KEY_GUEST_EMAIL + TEXT
            + COMMA + KEY_GUEST_DOB + TEXT + COMMA + KEY_GUEST_ANNIVERSARY + TEXT + COMMA
            + KEY_GUEST_SEX + TEXT + COMMA + KEY_GUEST_ADDRESS + TEXT
            + COMMA + KEY_GUEST_ADDRESS1 + TEXT + COMMA + KEY_GUEST_REMARK + TEXT + COMMA
            + KEY_GUEST_COMMENT + TEXT + FINISH_COLUMN;


    public static final String CREATE_GUEST_FEEDBACK_TABLE = CREATE_TABLE_BASE
            + KEY_GUEST_FEEDBACK_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_GUEST_FEEDBACK_CC_PARA + TEXT + COMMA
            + KEY_GUEST_FEEDBACK_CC_RATING + TEXT + COMMA + KEY_GUEST_FEEDBACK_CC_FLAG
            + TEXT + COMMA + KEY_GUEST_FEEDBACK_CC_GRP + TEXT + COMMA + KEY_GUEST_FEEDBACK_CC_SEL
            + TEXT + FINISH_COLUMN;


    public static final String CREATE_GUEST_ORDER_TABLE = CREATE_TABLE_BASE
            + KEY_GUEST_ORDER_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_GUEST_ORDER_NUMBER + TEXT + COMMA
            + KEY_GUEST_ORDER_ITEMS + TEXT + COMMA + KEY_GUEST_ORDER_AMT + TEXT + COMMA
            + KEY_GUEST_ORDER_TABLE_NO + TEXT + COMMA + KEY_GUEST_ORDER_STATUS + TEXT + FINISH_COLUMN;


        public static final String CREATE_GUEST_ORDERS_TABLE = CREATE_TABLE_BASE
                + KEY_GUEST_ORDERS_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
                + AUTO_ICNREMENT + COMMA + KEY_ORDER_NUMBER + TEXT + COMMA
                + KEY_TABLE_NUMBER + TEXT + COMMA + KEY_ITEM_CODE + TEXT + COMMA
                + KEY_ITEM_NAME + TEXT + COMMA + KEY_ITEM_PRICE + TEXT + COMMA
                + KEY_ITEM_QTY + TEXT + COMMA + KEY_ORDER_TAX + TEXT + COMMA + KEY_ORDER_AMOUNT + TEXT
                + COMMA + KEY_ORDER_STATUS + TEXT + COMMA + KEY_ORDER_DATE + TEXT + COMMA
                + KEY_ORDER_TIME + TEXT + FINISH_COLUMN;


    public static final String CREATE_MENU_FTS = "CREATE VIRTUAL TABLE  Menu_Item_Table_fts USING fts3("
            + KEY_MENU_POS_CODE
            + ","
            + KEY_MENU_CODE
            + ","
            + KEY_MENU_NAME
            + ","
            + KEY_MENU_CAT_CODE
            + ","
            + KEY_MENU_COLOR
            + ","
            + KEY_MENU_GRP_CODE
            + ","
            + KEY_MENU_PRICE
            + ","
            + KEY_MENU_VAT
            + ","
            + KEY_MENU_SUB_UNIT
            + ","
            + KEY_MENU_COMBO_FLAG
            + ","
            + KEY_MENU_ADDON_FLAG
            + ","
            + KEY_MENU_MODIFIER
            + ","
            + KEY_MENU_OPEN_ITEM
            + ","
            + KEY_MENU_SUB_ITEM
            + ","
            + KEY_MENU_VEG_NON
            + ","
            + KEY_MENU_CALORIES
            + "," + " UNIQUE (" + KEY_MENU_CODE + "));";


    public static final String CREATE_GUEST_SEARCH_FTS = "CREATE VIRTUAL TABLE  guestsearch_fts USING fts3("

            + KEY_GUEST_NAME
            + ","
            + KEY_GUEST_PHONE
            + ","
            + KEY_GUEST_EMAIL
            + ","
            + KEY_GUEST_SEX
            + ","
            + KEY_GUEST_ADDRESS
            + ","
            + KEY_GUEST_ADDRESS1
            + ","
            + KEY_GUEST_REMARK
            + ","
            + " UNIQUE ("
            + KEY_GUEST_PHONE + "));";


    public static final String CREATE_RMS_COMPANY_TABLE = CREATE_TABLE_BASE
            + KEY_RMS_COMPANY_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_COMPANY_COMP_CODE + TEXT + COMMA
            + KEY_COMPANY_COMP_NAME + TEXT + COMMA + KEY_COMPANY_COMP_ADD1
            + TEXT + COMMA + KEY_COMPANY_COMP_ADD2 + TEXT + COMMA
            + KEY_COMPANY_COMP_CITY + TEXT + COMMA + KEY_COMPANY_COMP_PIN
            + TEXT + COMMA + KEY_COMPANY_COMP_EMAIL + TEXT + COMMA
            + KEY_COMPANY_COMP_CL + TEXT + COMMA + KEY_COMPANY_COMP_PAN_NO + TEXT + COMMA + KEY_COMPANY_COMP_ID + TEXT + COMMA
            + KEY_COMPANY_COMP_PHONE1 + TEXT + COMMA + KEY_COMPANY_COMP_VNO
            + TEXT + COMMA + KEY_COMPANY_COMP_COMMENT + TEXT
            + COMMA + KEY_COMPANY_COMP_PIC + TEXT + COMMA + KEY_COMPANY_COMP_CAT + TEXT + COMMA
            + KEY_COMPANY_COMP_ARR_DATE + TEXT + COMMA + KEY_COMPANY_COMP_DEP_DATE
            + TEXT + COMMA + KEY_COMPANY_COMP_STS + TEXT + COMMA + KEY_COMPANY_COMP_INFO_DATE + TEXT + COMMA + KEY_COMPANY_COMP_LOYALTY_DATE + TEXT + FINISH_COLUMN;


    public static final String CREATE_FLOOR_IMAGE_TABLE = CREATE_TABLE_BASE
            + KEY_FLOOR_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_FLOOR_POS + TEXT + COMMA
            + KEY_FLOOR_SELECTION + TEXT + COMMA
            + KEY_FLOOR_IMAGE_NAME + TEXT + COMMA
            + KEY_FLOOR_IMAGE_X + TEXT + COMMA + KEY_FLOOR_IMAGE_Y
            + TEXT + COMMA + KEY_FLOOR_IMAGE_SCALE_X
            + TEXT + COMMA + KEY_FLOOR_IMAGE_SCALE_Y
            + TEXT + COMMA + KEY_FLOOR_IMAGE_SCALE_ANGLE
            + TEXT + COMMA + KEY_FLOOR_IMAGE_WIDTH
            + TEXT + COMMA + KEY_FLOOR_IMAGE_HEIGHT
            + TEXT + COMMA + KEY_FLOOR_IMAGE_DWIDTH
            + TEXT + COMMA + KEY_FLOOR_IMAGE_DHEIGHT
            + TEXT + COMMA + KEY_FLOOR_MMINX
            + TEXT + COMMA + KEY_FLOOR_MMAXX
            + TEXT + COMMA + KEY_FLOOR_MMINY
            + TEXT + COMMA + KEY_FLOOR_MMAXY
            + TEXT + COMMA + KEY_FLOOR_MISGRABAREASELECTED
            + TEXT + COMMA + KEY_FLOOR_MISLATESTSELECTED
            + TEXT + COMMA + KEY_FLOOR_MGRABAREAX1
            + TEXT + COMMA + KEY_FLOOR_MGRABAREAY1
            + TEXT + COMMA + KEY_FLOOR_MGRABAREAX2
            + TEXT + COMMA + KEY_FLOOR_MGRABAREAY2
            + TEXT + COMMA + KEY_FLOOR_MSTARTMIDX
            + TEXT + COMMA + KEY_FLOOR_MSTARTMIDY
            + TEXT + COMMA + KEY_FLOOR_INTRINSICWIDTH
            + TEXT + COMMA + KEY_FLOOR_INTRINSICHEIGHT
            + TEXT + COMMA + KEY_FLOOR_IS_FIRST_LOAD
            + TEXT + COMMA + KEY_FLOOR_UI_MODE_ROTATE
            + TEXT + COMMA + KEY_FLOOR_UI_MODE_ANISOTROPIC_SCALE
            + TEXT + COMMA + KEY_FLOOR_UI_MUIMODE
            + TEXT + COMMA + KEY_FLOOR_IMAGE_TEXT
            + TEXT + FINISH_COLUMN;


    public static final String CREATE_FLR_TBL_TABLE = CREATE_TABLE_BASE
            + KEY_TBLTABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_TBL_RMSC_POP + TEXT + COMMA
            + KEY_TBL_RMSC_COD + TEXT + COMMA + KEY_TBL_RMSC_STD
            + TEXT + COMMA + KEY_TBL_RMSC_BCOLOR
            + TEXT + COMMA + KEY_TBL_RMSC_FLOOR
            + TEXT + COMMA + KEY_TBL_RMSC_ROW
            + TEXT + COMMA + KEY_TBL_RMSC_COLUMN
            + TEXT + COMMA + KEY_TBL_RMSC_SHAPE + TEXT + FINISH_COLUMN;

    public static final String CREATE_FLR_FLOOR_TABLE = CREATE_TABLE_BASE
            + KEY_FLR_FLOOR + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_FLR_FLOOR_CODE + TEXT + COMMA
            + KEY_FLR_FLOOR_DESC + TEXT + COMMA + KEY_FLR_FLOOR_PIC
            + TEXT + COMMA + KEY_FLR_FLOOR_STATUS
            + TEXT + COMMA + KEY_FLR_RMS_FLOOR_MST
            + TEXT + FINISH_COLUMN;


    public static final String KEY_CHECK_SETTING_TABLE = CREATE_TABLE_BASE
            + KEY_ATTRIBUTE_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_CHECK_HOME_ORDER_GUEST_MANDATE + TEXT + COMMA
            + KEY_CHECK_HOME_HOLD_ORDER + TEXT + COMMA + KEY_CHECK_MULTI_QTY + TEXT + COMMA
            + KEY_CHECK_FORM_TYPE + TEXT + COMMA + KEY_CHECK_BILL_SETTLE + TEXT + COMMA
            + KEY_CHECK_BILL_SETTLE_MANDATE + TEXT + COMMA + KEY_CHECK_PER_ORDER_LOGIN + TEXT + COMMA
            + KEY_NO_REASON_ORDER_MODIFICATION + TEXT + COMMA + KEY_PRINT_CANCEL_MODIFY + TEXT + COMMA
            + KEY_ORDER_REMARK_MANDATORY + TEXT + COMMA + KEY_NO_REASON_BILL_MODIFICATION + TEXT + COMMA
            + KEY_NO_GENERATE_STW_BILL + TEXT + COMMA + KEY_ACTIVATE_REMARK_AS_GUEST + TEXT + COMMA
            + KEY_GROUP_WISE_BILLING + TEXT + COMMA + KEY_HIDE_BILL_REMARK + TEXT + COMMA
            + KEY_NO_DELETE_BTN_BILL_EDIT + TEXT + COMMA + KEY_NO_MODIFY_BTN_BILL_EDIT + TEXT + COMMA
            + KEY_DISCOUNT_REASON_MANDATORY + TEXT + FINISH_COLUMN;


    public static final String CREATE_TABLE_IMAGE = CREATE_TABLE_BASE
            + IMAGE_TABLE + START_COLUMN + IMAGE_NAME  + TEXT + COMMA + IMAGE_DATA + " BLOB" + FINISH_COLUMN;

    public static final String CREATE_CURRENCY_TABLE = CREATE_TABLE_BASE
            + KEY_CURRENCY_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + KEY_CURRENCY_SR + TEXT + COMMA
            + KEY_CURRENCY_LABEL + TEXT + COMMA + KEY_CURRENCY_VALUE + TEXT + COMMA
            + KEY_CURRENCY_FLAG + TEXT + COMMA + KEY_CURRENCY_PIC + TEXT
            + FINISH_COLUMN;


        public static final String CREATE_ITEMS_TABLE = CREATE_TABLE_BASE
            + ITEMS_DETAIL_TABLE + START_COLUMN + _ID + INTEGER + PRIMARY_KEY
            + AUTO_ICNREMENT + COMMA + Current_Rate + TEXT + COMMA
            + Inc_Qty + TEXT + COMMA + Inc_Rate + TEXT + COMMA
            + Item_Desc + TEXT + COMMA + Max_Price + TEXT + COMMA
            + Min_Price + TEXT + COMMA + Previous_Rate + TEXT + COMMA
            + Sold_Qty + TEXT + COMMA + Today_Max + TEXT + COMMA
            + Cat_Code + TEXT + COMMA + Cat_Desc + TEXT + COMMA
            + Item_Code + TEXT + FINISH_COLUMN;


}